IF:
  n_estimators: 200
  max_samples: 0.8
  contamination: 0.45
  bootstrap: True

LOF:
  n_neighbors: 50
  contamination: 0.5
  novelty: True

DBSCAN:
  eps: 5.0
  min_samples: 2

KMeans:
  n_clusters: 4
  n_init: 20

OCSVM:
  kernel: rbf
  gamma: scale
  nu: 0.5

KNN:
  n_neighbors: 49
  p: 2

SVM:
  C: 1.0
  kernel: rbf
  gamma: scale